apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: consumer
spec:
  selector:
    app: consumer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
