kind: Service
apiVersion: v1
metadata:
  name: frontend-eventstore
  namespace: eventstore
spec:
  selector:
    app: frontend-eventstore
  ports:
    - protocol: "TCP"
      port: 2113
      targetPort: 2113
  type: LoadBalancer