ingress:
  annotations:
    kubernetes.io/ingress.class: nginx

service:
  type: ClusterIP

ui:
  ingress:
    enabled: true
    path: /
    hosts:
      - seq.mydomain.com

ingestion:
  ingress:
    enabled: true
    path: /
    hosts:
      - ingestion.seq.mydomain.com

gelf:
  enabled: true
  service:
    port: 12201
    protocol: TCP